# Generated by Django 4.1.6 on 2023-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='none', max_length=50)),
                ('idade', models.IntegerField()),
                ('raiva', models.IntegerField()),
            ],
        ),
    ]
